### ISSUE TITLE
Negative Number is possible

### ISSUE THREAD

**Issue by mpagels** [CJAkkuec/dnd-bench#11]
When creating a new character, it is possible to put a negative number in the `Basics` `level` input.

![grafik](https://user-images.githubusercontent.com/54703643/141993954-62ef7676-580e-4efa-979e-95a1a8ccf16a.png)

**Comment by mpagels** [comment]
Found out, that this is also in other number inputs possible.

**Comment by CJAkkuec** [comment]
Sometimes it's intended, but I have to check. : )
