### ISSUE TITLE
Can save an empty string as character name

### ISSUE THREAD

**Issue by mpagels** [CJAkkuec/dnd-bench#12]
It is possible, to save an empty string as a character name.

![grafik](https://user-images.githubusercontent.com/54703643/141994218-213fb85a-331f-4638-aafb-f01b9c5e70a1.png)

**Comment by CJAkkuec** [comment]
React Hook Form Validate

**Comment by CJAkkuec** [comment]
After giving it some thought, I'll be allowing empty strings.
