### ISSUE TITLE
Last character on bench is not shown, when list is long 

### ISSUE THREAD

**Issue by mpagels** [CJAkkuec/dnd-bench#13]
## Value statement - a requirement, not a solution
As a **user** 
I need **a margin at the bottom** 
so that **I can see all of my characters, when the list is long** 

## Description (Text, Scribble, Wireframe, Design)
When having a lot of characters on my bench, the last one is not shown, because the `navBar` is over it.

https://user-images.githubusercontent.com/54703643/141995102-20262ea6-a200-42ec-b7df-2ebb8096548a.mp4

## Acceptance criteria
- [x] when the list is long, the last item should be shown

## Tasks
- [x] add a margin to the list, at least the `height` of the `navbar`
## Size

(small)

**Comment by CJAkkuec** [comment]
Done and done. :)
