### ISSUE TITLE
Whole Container clickable

### ISSUE THREAD

**Issue by mpagels** [CJAkkuec/dnd-bench#8]
## Value statement - a requirement, not a solution
As a **user** 
I need **the whole container, clickable** 
so that **I'm not confused** 

## Description (Text, Scribble, Wireframe, Design)
Right now, the accordion buttons are only clickable when clicking on the name. But it would be a better UX, if the entire space was clickable. See GIF.

![2021-11-16-14-08-48](https://user-images.githubusercontent.com/54703643/141992264-268af4a1-aa68-4485-8dcc-75d8f8e66e6b.gif)

## Acceptance criteria
- [x] When clicked on the entire container, the area opens
- [ ] When clicked on the entire container, when open, the ares closes

## Tasks
-

## Size
(small)

**Comment by CJAkkuec** [comment]
The entire container is now clickable when the it's closed, though I prefer the trigger to be just the descriptor when the container is open.
